### ISSUE TITLE
Wallet connection is flaky

### ISSUE THREAD

**Issue by statictype** [paritytech/link#265]
The connected state is lost after page refresh.

https://github.com/paritytech/link/assets/42985153/35bd6695-4ab8-49ee-82bc-4e4c99550b8d

**Comment by DoubleOTheven** [comment]
This is an issue in useink. I have a fix and will release a new version. The solution is to check localStorage inside of `useEffect`, which is fired after the document is ready. Polkadot Wallet was slow to initialize some times. I was only able to reproduce the bug you found using Polkadot Wallet.

PR coming soon...
