### ISSUE TITLE
Form is disabled after connecting wallet

### ISSUE THREAD

**Issue by statictype** [paritytech/link#269]
If the user already pasted a URL in the field and connects the wallet via the button below, all inputs and submit button are disabled.

Note: doesn't happen if the user connects via the top right corner button or if the form is empty when clicking the button.

https://github.com/paritytech/link/assets/42985153/ec353a35-413a-4651-b7f1-772da1183ae2

**Comment by DoubleOTheven** [comment]
I see, Formik is treating it as a submit even though the button type is not 'submit'. `isSubmitting` gets set to `true`, which disables everything
