### ISSUE TITLE
Check if a signer extension is available

### ISSUE THREAD

**Issue by statictype** [paritytech/link#72]
Currently we assume users have the Polkadot.js extension in their browser. Other wallets haven't been tested. 
The user experience is very poor for first time users. There is no guide to install a compatible extension and create a new account.

**Comment by DoubleOTheven** [comment]
This is complete via useink

## If no wallet is installed

<img width="1920" alt="Screen Shot 2023-06-06 at 6 54 35 PM" src="https://github.com/paritytech/link/assets/2101499/126dafce-b2b3-4b1e-9c52-3e9c2bd82815">

## Let user choose one of the wallets they have installed

<img width="1918" alt="Screen Shot 2023-06-06 at 6 55 30 PM" src="https://github.com/paritytech/link/assets/2101499/8a954bc3-ba43-43c2-92a9-5a5ab2c428e5">
