### ISSUE TITLE
Use the currently selected address from the wallet in the faucet example

### ISSUE THREAD

**Issue by athei** [paritytech/link#94]
<img width="398" alt="Screenshot 2022-09-28 at 11 26 50" src="https://user-images.githubusercontent.com/2580396/192743088-39734e7a-b967-44e3-8b3e-8ea458ba9046.png">

We should use the concrete address from the wallet instead of `YOUR_SS_58_ADDRESS` to make it copy paste able.

**Comment by DoubleOTheven** [comment]
We now link to https://use.ink/faucet

It would be nice if we added a query param on the use.ink site to auto populate the form. Then in Link we can detect the user address and add it to the link

**Comment by DoubleOTheven** [comment]
I added the query param in [this PR](https://github.com/paritytech/ink-docs/pull/233). I will add it to this dApp now...
